/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:902f6cbd-9276-474b-87c2-bc23e0df7c1b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_mJzGDVihE",
    "aws_user_pools_web_client_id": "6blnv9hltp5he7g0pg53dpl6df",
    "oauth": {}
};


export default awsmobile;